const BLOCK_STRING__ELEM_STRING = <div className="BLOCK-ELEM" />;
const BLOCK_STRING__ELEM_STRING_EMPTY = <div className="BLOCK" />;
const BLOCK_STRING_EMPTY__ELEM_STRING = <div />;
const BLOCK_STRING_EMPTY__ELEM_STRING_EMPTY = <div />;
